#
# Portos v1.7.0
# Copyright (c) 2003-2014 by Rabih Chrabieh. All rights reserved.
#

VERSION    := test

DIR_TOP    := ..

CFILES     := $(wildcard *.c)
ALLFILES   := $(wildcard *)

include $(DIR_TOP)/makefile.def

all: depend  $(OBJS) $(DIR_OBJ)/po_test.exe

# Put this one last
include $(DIR_TOP)/makefile.inc
