#
# Copyright (c) 2003-2014 by Rabih Chrabieh. All rights reserved.
#

DIR_TOP    := ..

CFILES     := 
HFILES     := $(wildcard *.h target_*/*.h)
ALLFILES   := $(wildcard * target_*/*)

include $(DIR_TOP)/makefile.def

all:

# Put this one last
include $(DIR_TOP)/makefile.inc
